### ISSUE TITLE
bad KiCAD files

### ISSUE THREAD

**Issue by AnttiLukats** [myriadrf/reference-development-kit#1]
umyriadrf-6002
umyriadrf-7002

the KiCAD PCB files can not be opened, there comes an error about missing layer and the PCB remains empty

**Comment by championlee** [comment]
You need to use Kicad old stable version BZR4022 to open them. This version is still can be downloaded in http://kicad-pcb.org/download/windows/

**Comment by AnttiLukats** [comment]
would it not be better to FIX the pcb files? the other kicad files can be opened, only those 2 not

**Comment by championlee** [comment]
Although they are based BZR4022, I've tried still can be open without problem on latest stable version 4.0.2. Maybe you can check again on the right panel of PCBNEW to see whether the visibility checkbox for "missing layer" on layer page, and whether something (Pads, FootPrints, Text for Front/Back) are not selected on Render page.

**Comment by championlee** [comment]
Some people believe Kicad 4.0.x are still unstable or not function well. That's why these designs are still using old stable version.
